---
- hosts:
    - leafs
    - spines
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - networking
- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown
- hosts: server02
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - apache
